name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'static-web/**'
      - 'dynamic-app/**'
      - 'docker-compose.yml'

jobs:
  build-and-deploy-static:
    name: Static Web Pipeline
    runs-on: ubuntu-latest
    if: contains(toJSON(github.event.commits.*.modified), 'static-web') || contains(toJSON(github.event.commits.*.added), 'static-web')
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build & Push static-web
        uses: docker/build-push-action@v5
        with:
          context: ./static-web
          push: true
          tags: muhamadalghifari/static-web:latest
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/uas-2388010048
            docker compose pull static-web
            docker compose up -d static-web
            docker image prune -f

  build-and-deploy-dynamic:
    name: Dynamic App Pipeline
    runs-on: ubuntu-latest
    if: contains(toJSON(github.event.commits.*.modified), 'dynamic-app') || contains(toJSON(github.event.commits.*.added), 'dynamic-app')
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build & Push dynamic-app
        uses: docker/build-push-action@v5
        with:
          context: ./dynamic-app
          push: true
          tags: muhamadalghifari/dynamic-app:latest
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/uas-2388010048
            docker compose pull dynamic-app
            docker compose up -d dynamic-app
            docker image prune -f
